services:
  rabbitmq:
    image: "bitnami/rabbitmq-delayed-message-exchange:latest"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
PK
